### ISSUE TITLE
This line has more transparency (is lighter) in the designs

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#100]
![image](https://user-images.githubusercontent.com/1376815/80517178-f659f380-8984-11ea-9ee0-6f8486f945f2.png)

**Comment by ShkredovDmitriy** [comment]
I fixed this bug a few days ago

**Comment by lpissinali** [comment]
The problem here seems to be that the border on the design has only 0.5px width. Also please remove the top border of the container.
