### ISSUE TITLE
wrong size

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#109]
![image](https://user-images.githubusercontent.com/1376815/80517802-e55db200-8985-11ea-939e-33d6f533ef9d.png)

**Comment by donrus** [comment]
https://prnt.sc/s7t24x - sizes from design
.login__form-forgot-link {
    font-family: "SarabunBold", arial, sans-serif;
    font-size: 0.875rem;

**Comment by lpissinali** [comment]
That seems correct. As you can see his screenshot is outdated. Could you please align the text a bit better.
![image](https://user-images.githubusercontent.com/1376815/80579082-be48c400-8a09-11ea-9714-f283b959abf6.png)

**Comment by lpissinali** [comment]
Looking a second time I see that when I enter font size 14px the text actually shows bigger so I think we need to increase it. Same with the "remember me" text

![image](https://user-images.githubusercontent.com/1376815/80591363-e0e4d800-8a1d-11ea-8529-17a6f4e96b5b.png)
