### ISSUE TITLE
Flag alignment 

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#110]
Please center the "En" (not the g, because of the g it looks like its not centered

![image](https://user-images.githubusercontent.com/1376815/80517864-00c8bd00-8986-11ea-978a-68f4d7f05ef1.png)

**Comment by ShkredovDmitriy** [comment]
https://prnt.sc/s7v2kj, I fixed this bug a few days ago

**Comment by lpissinali** [comment]
I currently see it like this 
![image](https://user-images.githubusercontent.com/1376815/80581946-37e2b100-8a0e-11ea-9db7-78987b8af8fc.png)

**Comment by ShkredovDmitriy** [comment]
https://prnt.sc/s7x1g0, I raised the flag a few pixels in all resolutions
