### ISSUE TITLE
Reduce font weight

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#111]
![image](https://user-images.githubusercontent.com/1376815/80517985-2ce43e00-8986-11ea-9471-dce3a60855af.png)

**Comment by ShkredovDmitriy** [comment]
![изображение](https://user-images.githubusercontent.com/38492536/80576646-3b763800-8a0e-11ea-914f-415210b97ac5.png)
I fixed this bug a few days ago
