### ISSUE TITLE
Check font weight on all subheadlines

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#112]
![image](https://user-images.githubusercontent.com/1376815/80518090-4e452a00-8986-11ea-8f7e-e139ce763d45.png)

**Comment by ShkredovDmitriy** [comment]
https://prnt.sc/s7utp4, I fixed this bug a few days ago

**Comment by lpissinali** [comment]
Some pages still have bold.
![image](https://user-images.githubusercontent.com/1376815/80592181-4ab1b180-8a1f-11ea-846e-bc67c1595fee.png)
