### ISSUE TITLE
Laggy transition

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#114]
when you click on "details" the colors change to blue. this transition is currently laggy

![image](https://user-images.githubusercontent.com/1376815/80518191-72087000-8986-11ea-8261-512dc9cc54fb.png)

**Comment by ShkredovDmitriy** [comment]
I fixed this bug 3 days ago

**Comment by lpissinali** [comment]
I'll check if he still has problems.

**Comment by ShkredovDmitriy** [comment]
what should be done? remove transition&

**Comment by ShkredovDmitriy** [comment]
?

**Comment by lpissinali** [comment]
Just hold for now.

**Comment by lpissinali** [comment]
He still not happy with this, please see if you can do something. He sent a video
[lag (2).zip](https://github.com/lpissinali/bitbunch/files/4554427/lag.2.zip)

**Comment by lpissinali** [comment]
Also, the opening/close of the boxes he's complaining it's laggy. Here's another video and his comments.
"The last box works with nearly no a lag. But the more boxes there are over the actual box, the laggier it gets."

[laggy_faq_box.zip](https://github.com/lpissinali/bitbunch/files/4556376/laggy_faq_box.zip)

**Comment by lpissinali** [comment]
The careers show details doesn't expand now

**Comment by ShkredovDmitriy** [comment]
fixed, I turned off the shadow animation in the phones, it slowed down the opening of the list

**Comment by lpissinali** [comment]
Thanks, but still doesn't open

**Comment by ShkredovDmitriy** [comment]
sorry, I turned it off, forgot to turn it on, now it works

**Comment by lpissinali** [comment]
Thanks, let's see if he's happy now :)
