### ISSUE TITLE
Check font size/weight

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#115]
![image](https://user-images.githubusercontent.com/1376815/80518275-8fd5d500-8986-11ea-9b11-40d0a7b86e44.png)

**Comment by ShkredovDmitriy** [comment]
![изображение](https://user-images.githubusercontent.com/38492536/80574449-82fac500-8a0a-11ea-99c2-55b0f8d48e9f.png)
I fixed this bug yesterday
