### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#122]
For all pages where we did not specify any animations, please just let it fade in on scroll. But only the things not visible. 

So e.g. on the reg page on mobile, you will of course see the reg form and the orange button. But when you scroll down, the other elements will fade in. Should work on all devices, not just mobile

**Comment by donrus** [comment]
I add animation, but on these pages, I mean login and register, there is only protection block to animate

**Comment by lpissinali** [comment]
I guess that's fine.
