### ISSUE TITLE
This whole section (animation and the description over it) must always fit into the same screen.

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#126]
![image](https://user-images.githubusercontent.com/1376815/80871861-a0e85400-8cae-11ea-8674-fabd856c98d4.png)

**Comment by ShkredovDmitriy** [comment]
did not understand what needs to be done?

**Comment by lpissinali** [comment]
If possible the slider and the image should be visible on the screen at the same time.
![image](https://user-images.githubusercontent.com/1376815/80961732-d8204780-8e0b-11ea-9267-5e83c5f1fd74.png)

**Comment by ShkredovDmitriy** [comment]
https://prnt.sc/sao50x, https://prnt.sc/sao6k9, I can reduce the picture
