### ISSUE TITLE
The pulsing should never stop and the circle should be bigger when pulsing

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#144]
![image](https://user-images.githubusercontent.com/1376815/80978648-a1a3f600-8e26-11ea-95f3-b7b70bb6c455.png)

**Comment by lpissinali** [comment]
Also please make the slides loop. When you are on 4 and click on next it goes to 1

**Comment by lpissinali** [comment]
It's not pulsing on the left arrow.

**Comment by ShkredovDmitriy** [comment]
add animation to left arrow
