### ISSUE TITLE
On all pages the backgrounds should take the full width, not the content.

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#146]
![image](https://user-images.githubusercontent.com/1376815/80988498-e1250f00-8e33-11ea-91a5-ce3d22c934d1.png)

**Comment by donrus** [comment]
We need all background pictures for width 1920 px. And for pages Home, HIW, Pressroom, Team there need to be a designs, because some elements are behind the visible area.

**Comment by lpissinali** [comment]
we should at least cover 32 inch, so the page looks good on most desktop screens.
I think the only issue will be on team (just ignore team for now for this task)
Will you need bigger waves for 32"?

**Comment by ShkredovDmitriy** [comment]
I created a branch fullscreen, please look at the page HIW

**Comment by lpissinali** [comment]
I think it's a good start but as we know some backgrounds loose quality, like the background on the top header, so I'll point this out to him and ask his feedback. Hold on this for now.

**Comment by lpissinali** [comment]
Please proceed with this as you have done on the fullscreen branch

**Comment by ShkredovDmitriy** [comment]
I finished the task, please look at the branch fullscreen

**Comment by lpissinali** [comment]
Nice job, please fix some elements that are too wide:

Is the following one an issue because of the footer background? If so leave it as it is
![image](https://user-images.githubusercontent.com/1376815/81822551-90986a80-9533-11ea-989e-9fa8d1e8acc4.png)


Fix if possible:
![image](https://user-images.githubusercontent.com/1376815/81822634-ac037580-9533-11ea-84f2-374aa910bd8a.png)


Then please merge it to master and I'll ask him if he needs more fixes.
