### ISSUE TITLE
Calculation fixes

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#147]
- [x] Update the logos for ETH and USDT
- [x] The "your profit" unit should be updated when the user switch
- [x] The USDT range should go from 0 to 1,5 millions

![image](https://user-images.githubusercontent.com/1376815/81077113-d5495380-8eec-11ea-95b3-311ca0672267.png)

**Comment by ShkredovDmitriy** [comment]
1. where to download logos?

**Comment by lpissinali** [comment]
ETH was on the same file as the other images on the other bug and USDT I'll send here in a minute

**Comment by lpissinali** [comment]
It should be this one can you get from avocode? 
![image](https://user-images.githubusercontent.com/1376815/81082961-3f192b80-8ef4-11ea-99bb-ef71f1a725a3.png)

**Comment by lpissinali** [comment]
[usdt-logo.zip](https://github.com/lpissinali/bitbunch/files/4581714/usdt-logo.zip)

**Comment by ShkredovDmitriy** [comment]
done
