### ISSUE TITLE
Low quality images

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#148]
I know we updated those images before but the client still complaining about its quality, can you please verify that we have the best possible quality?
[items.zip](https://github.com/lpissinali/bitbunch/files/4581318/items.zip)

**Comment by ShkredovDmitriy** [comment]
https://prnt.sc/sbcvh6, I opened the file in avocode and saw only one picture

**Comment by lpissinali** [comment]
It should be those. Please let me know if you need better quality

[Downloads.zip](https://github.com/lpissinali/bitbunch/files/4581605/Downloads.zip)

**Comment by lpissinali** [comment]
[Downloads.zip](https://github.com/lpissinali/bitbunch/files/4581646/Downloads.zip)

**Comment by ShkredovDmitriy** [comment]
done, I think we need to replace this picture too, https://prnt.sc/sbegzl

**Comment by lpissinali** [comment]
I sent this one too right?

**Comment by ShkredovDmitriy** [comment]
No, you send me his - 
![изображение](https://user-images.githubusercontent.com/38492536/81094480-3b919e80-8f0c-11ea-9e1b-e9823bbd3cc0.png)

**Comment by ShkredovDmitriy** [comment]
this image for desktop

**Comment by lpissinali** [comment]
I couldn't find this image so we leave it for now.
