### ISSUE TITLE
Label doesn't go up after selection

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#170]
![image](https://user-images.githubusercontent.com/1376815/81401901-99063500-9130-11ea-928f-a23219d8846d.png)

**Comment by lpissinali** [comment]
When you first enter the page the first name and last name are already up
![image](https://user-images.githubusercontent.com/1376815/81579298-4c2e9280-93ac-11ea-9d51-199cfdd54368.png)

**Comment by donrus** [comment]
fixed
