### ISSUE TITLE
when I scroll to the very right, the text is cut off (increase space to the border)

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#187]
![image](https://user-images.githubusercontent.com/1376815/81476598-01c5de00-9213-11ea-9b2f-dfd283eedc8e.png)

**Comment by donrus** [comment]
fixed

**Comment by lpissinali** [comment]
Still very close to the edge, also on the left side it's not aligned.

![image](https://user-images.githubusercontent.com/1376815/81591416-b2231600-93bc-11ea-9b46-6721596957a0.png)

And I don't see the navigation bar as it should
![image](https://user-images.githubusercontent.com/1376815/81591496-cd8e2100-93bc-11ea-88fb-0be67ad49ea9.png)

**Comment by donrus** [comment]
fixed
