### ISSUE TITLE
Please allign the up/down arrows vertically (currently the arrows and the % are centered to the right)

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#193]
![image](https://user-images.githubusercontent.com/1376815/81476714-a2b49900-9213-11ea-8445-3bccfc857711.png)

**Comment by donrus** [comment]
It's just markup. In Drupal template they could insert any amount of digits to be alligned.

**Comment by lpissinali** [comment]
Please make it always aligned as if it was a separate column independent of the number of digits. 
![image](https://user-images.githubusercontent.com/1376815/81648744-79705480-942f-11ea-9d9c-0537a77ff656.png)

**Comment by donrus** [comment]
fixed
