### ISSUE TITLE
please add the right dropdown animation

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#204]
![image](https://user-images.githubusercontent.com/1376815/81477279-363b9900-9217-11ea-955d-55681d36bbbd.png)

**Comment by donrus** [comment]
Could you give the sample of animation the dropdown.

**Comment by lpissinali** [comment]
Make the same as on the FAQ page but as a dropdown instead of accordion

**Comment by donrus** [comment]
fixed
