### ISSUE TITLE
it's laggy when you select an asset (it shows other assets first)

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#205]
![image](https://user-images.githubusercontent.com/1376815/81477344-b19d4a80-9217-11ea-9680-a113e49171e5.png)

**Comment by donrus** [comment]
What do they mean?

**Comment by lpissinali** [comment]
I believe when you switch assets you can see some weird animation

**Comment by lpissinali** [comment]
I'll close this for now and if he complains we reopen it.
