### ISSUE TITLE
Improve dropdown

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#209]
currently this dropdown feels very static (like it was just an image of a dropdown), because no matter where you are with the mouse courser, it is always clickable. 

Can you try to add a light hover effect? Like we have it on the table of the HIW page, just much much less. 

![image](https://user-images.githubusercontent.com/1376815/81477435-16f13b80-9218-11ea-8bf9-9139a0a269fe.png)

**Comment by donrus** [comment]
fixed
