### ISSUE TITLE
The "asset" dropdown has the same effect as the "how much can I earn" calculator on the HIW page. So when you choose "Ethereum" it should say "Fund your Ethereum wallet" and the B graphic in the right corner should change (I will send you the right graphic for ETH and USDT)

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#211]
![image](https://user-images.githubusercontent.com/1376815/81477481-4738da00-9218-11ea-86ea-dd27653dae68.png)

**Comment by donrus** [comment]
fixed

**Comment by lpissinali** [comment]
It's missing change the background image
![image](https://user-images.githubusercontent.com/1376815/81649927-5d6db280-9431-11ea-8391-a0af1050ee03.png)

**Comment by donrus** [comment]
Could you send the backgrounds for ETH and USDT

**Comment by lpissinali** [comment]
![usdt@2x](https://user-images.githubusercontent.com/1376815/81802321-22917a80-9516-11ea-966a-3376ed7a3094.png)
![eth@2x](https://user-images.githubusercontent.com/1376815/81802322-232a1100-9516-11ea-9033-26d9e52a0a73.png)
 Please see if you can use those or extract from here: 

[Date picker + logos.zip](https://github.com/lpissinali/bitbunch/files/4621352/Date.picker.%2B.logos.zip)
