### ISSUE TITLE
the mobile font size for the text in the button is too small, it should always be 14px like in the design. Please choose it everywhere (popup, "copy" on invest, etc)

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#221]
Maybe it's better to use pixels instead of rem because when the client sees on some devices it converts to smaller font sizes and he complains.

![image](https://user-images.githubusercontent.com/1376815/81477752-b531d100-9219-11ea-8f2c-190d36a5f770.png)

**Comment by donrus** [comment]
fixed
