### ISSUE TITLE
please dont always load the whole page

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#228]
no matter what you click in the user area, the whole page always loads again (with the loader). please dont always load the whole page again but only load the right content (so the menu always stays there). maybe preload everything so you can click through the whole user area without having to reload everything over and over again

**Comment by donrus** [comment]
We couldn't do it. So if you can try change his mind about this feature.

**Comment by lpissinali** [comment]
We need to find a way. He sent some suggestions...

https://pixinvent.com/apex-angular-4-bootstrap-admin-template/demo-1/inbox
https://themeforest.net/item/apex-angular-4-bootstrap-admin-template/20774875

Apex admin template comes with AOT and Lazy Loading. With AOT, the browser downloads a pre-compiled version of the application. The browser loads executable code so it can render the application immediately, without waiting to compile the app first. With Lazy Loading, it allows you to load JavaScript components asynchronously when a specific route is activated.

**Comment by donrus** [comment]
The only way we could do it is tabs. We did only markup, not the app.
