### ISSUE TITLE
Please move the CTA on all mobile resolutions fully above the fold

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#23]
![image](https://user-images.githubusercontent.com/1376815/79976793-7cfe6480-849d-11ea-92f4-4f3767c87104.png)

**Comment by ShkredovDmitriy** [comment]
Sorry, but i can't understand what is CTA.

**Comment by lpissinali** [comment]
That's call to action. In this case the button should be visible on mobile if possible

**Comment by ShkredovDmitriy** [comment]
done
