### ISSUE TITLE
this blue line between the box and the dropdown is wrong, please make it like on the registration page

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#239]
![image](https://user-images.githubusercontent.com/1376815/81478147-b06e1c80-921b-11ea-83ac-9263563e4255.png)

**Comment by donrus** [comment]
On the registration page select is without border. This is screenshot from design https://prnt.sc/serfif

**Comment by lpissinali** [comment]
I think he means that he doesn't what to see this line when the dropdown is open. You're right, on registration the fields don't have borders.


![image](https://user-images.githubusercontent.com/1376815/81577757-2607f300-93aa-11ea-801a-07171964398a.png)

**Comment by donrus** [comment]
fixed
