### ISSUE TITLE
Please change the preloader

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#245]
on some browsers / devices there is a bug with the preloader (check attached video). Please change the preloader to the one that I have attached as screenshot, you can see it here https://loading.io/css/

![image](https://user-images.githubusercontent.com/1376815/81656364-40d47900-9437-11ea-9efe-baead42eb7a1.png)
[preload_bug.zip](https://github.com/lpissinali/bitbunch/files/4614133/preload_bug.zip)

**Comment by ShkredovDmitriy** [comment]
done
