### ISSUE TITLE
the white fill of the B is missing and the whole image looks pixelated

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#253]
![image](https://user-images.githubusercontent.com/1376815/81780363-b2273100-94f6-11ea-9351-62633c391699.png)

**Comment by ShkredovDmitriy** [comment]
give me these pictures in 2x quality

**Comment by lpissinali** [comment]
I sent svgs

**Comment by lpissinali** [comment]
[Downloads.zip](https://github.com/lpissinali/bitbunch/files/4620897/Downloads.zip)

**Comment by ShkredovDmitriy** [comment]
done
