### ISSUE TITLE
still blurred, please check the attached image

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#254]
![image](https://user-images.githubusercontent.com/1376815/81780552-fca8ad80-94f6-11ea-86dd-99aa82480e88.png)

**Comment by ShkredovDmitriy** [comment]
![изображение](https://user-images.githubusercontent.com/38492536/81794837-0ee51480-9514-11ea-8877-f10c85cd2df0.png)

**Comment by ShkredovDmitriy** [comment]
please clean the cache

**Comment by lpissinali** [comment]
![image](https://user-images.githubusercontent.com/1376815/81802639-bcf1be00-9516-11ea-8235-5d4ed9531009.png)
