### ISSUE TITLE
should be centred  (27" screen)

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#265]
![image](https://user-images.githubusercontent.com/1376815/82036537-4c2add00-96a1-11ea-9fcd-5208f49e9186.png)

**Comment by lpissinali** [comment]
It's better but still could be more to the left, aligning the right of the image with the content, like this
![image](https://user-images.githubusercontent.com/1376815/82158454-40e5d600-9888-11ea-8ca2-61a0f0cac64b.png)


Like that is cutting the image on tablet
![image](https://user-images.githubusercontent.com/1376815/82158464-55c26980-9888-11ea-86ae-94fcb9caa21a.png)

**Comment by ShkredovDmitriy** [comment]
look, is it ok now?

**Comment by lpissinali** [comment]
Still cuts a bit on tablet. I'll send it to him and see if he complains.
