### ISSUE TITLE
this part should stay "centered"  (27" screen)

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#266]
![image](https://user-images.githubusercontent.com/1376815/82036990-d70bd780-96a1-11ea-9342-8f0347368f0e.png)

Here's the full image

[Group 52.zip](https://github.com/lpissinali/bitbunch/files/4633608/Group.52.zip)

**Comment by ShkredovDmitriy** [comment]
please look, is it ok now?

**Comment by lpissinali** [comment]
I hope so.
