### ISSUE TITLE
wrong position, text need to be on blue background  (27" screen)

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#268]
![image](https://user-images.githubusercontent.com/1376815/82037193-1803ec00-96a2-11ea-8178-bdd916a68c11.png)

**Comment by ShkredovDmitriy** [comment]
How to solve this problem? I can offer https://prnt.sc/sj29ik, but I do not like this solution.

**Comment by lpissinali** [comment]
Can you try do like this
![image](https://user-images.githubusercontent.com/1376815/82254586-625fc400-9953-11ea-85cb-f85382af857a.png)

**Comment by ShkredovDmitriy** [comment]
I got this result https://prnt.sc/sji28o, had to edit svg images in adobe illustrator

**Comment by lpissinali** [comment]
I sent svg's for you, didn't I? Also why the font on those banners is wrong?

**Comment by ShkredovDmitriy** [comment]
I forgot to send the changes. I did not receive a svg.

**Comment by lpissinali** [comment]
[dropdown.zip](https://github.com/lpissinali/bitbunch/files/4650176/dropdown.zip)
