### ISSUE TITLE
should be more on the left (27" screen)

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#270]
![image](https://user-images.githubusercontent.com/1376815/82037488-80eb6400-96a2-11ea-9186-09a6ea0eb853.png)

**Comment by ShkredovDmitriy** [comment]
https://prnt.sc/shua1l, how much to move?

**Comment by lpissinali** [comment]
He didn't specify but I would have the logos finishing aligned with the content and then have the container continue blank.
![image](https://user-images.githubusercontent.com/1376815/82126851-b2058a80-97af-11ea-95f1-c47ee54a7eee.png)

**Comment by lpissinali** [comment]
This was my idea, are you able to achieve it?
![image](https://user-images.githubusercontent.com/1376815/82158326-70e0a980-9887-11ea-867a-015cc4b6efe1.png)

**Comment by lpissinali** [comment]
But because I'm not sure if that's what he want, let me double check first.
