### ISSUE TITLE
not at the right posisiton  (27" screen)

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#271]
![image](https://user-images.githubusercontent.com/1376815/82037546-92347080-96a2-11ea-8207-959aba29d073.png)

**Comment by ShkredovDmitriy** [comment]
How to solve this problem? I can offer https://prnt.sc/sj29ik, but I do not like this solution.

**Comment by lpissinali** [comment]
Not good, I'll ask, hold on that.

**Comment by lpissinali** [comment]
The banners should move from the left and stop more to the left inside the content area. I believe it should be ok if they don't go all the way to the right side of the screen.

**Comment by donrus** [comment]
Could you send a screenshot of desired view?

**Comment by lpissinali** [comment]
Leave the position and the animation as it is for now, just don't show cut banners like this
![image](https://user-images.githubusercontent.com/1376815/82408771-9da1e600-9a6c-11ea-8042-8440c5f37ea2.png)
