### ISSUE TITLE
there is a strange shadow under the coin logos on some devices

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#278]
![image](https://user-images.githubusercontent.com/1376815/82060971-60360500-96c8-11ea-9bed-e976db4244b9.png)

**Comment by donrus** [comment]
What device is this bug at?

**Comment by lpissinali** [comment]
Mac OS

**Comment by donrus** [comment]
We can't repeat this neither on Macbook nor iPhone.
