### ISSUE TITLE
the click on the first article is not working on mobile/tablet

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#283]
![image](https://user-images.githubusercontent.com/1376815/82061330-d9cdf300-96c8-11ea-966f-5a64b78c4a56.png)

**Comment by ShkredovDmitriy** [comment]
what should happen when you click on?

**Comment by lpissinali** [comment]
Just needs to have a dummy link `<a href="#">` right now it's a div

**Comment by ShkredovDmitriy** [comment]
fixed
