### ISSUE TITLE
The dropdown menu and the parts around it (e.g. the blurry part) often have lags and are not smooth. Check the attached video

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#298]
[lag_dropdown.zip](https://github.com/lpissinali/bitbunch/files/4654828/lag_dropdown.zip)

**Comment by donrus** [comment]
We can't repeat this neither on Macbook nor iPhone.

**Comment by donrus** [comment]
Or do you mean changing bg of wallet section and QR?
