### ISSUE TITLE
Wrong alignment

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#3]
![Screenshot_3](https://user-images.githubusercontent.com/1376815/79628323-50b2b300-8140-11ea-85cb-85fd0c614efb.png)

**Comment by ShkredovDmitriy** [comment]
fixed

**Comment by lpissinali** [comment]
There should also be a misalignment on those other boxes 
![image](https://user-images.githubusercontent.com/1376815/79761516-dc376a00-8321-11ea-83ec-57a8f2f92922.png)

**Comment by ShkredovDmitriy** [comment]
done
