### ISSUE TITLE
the popups still have the old error notification

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#302]
the popups still have the old error notification
![image](https://user-images.githubusercontent.com/1376815/82423525-2415f200-9a84-11ea-9674-c84c68ea931c.png)

**Comment by donrus** [comment]
I couldn't open sketch. Could you send texts?

**Comment by lpissinali** [comment]
The problem isn't the text, it how it should look like
![image](https://user-images.githubusercontent.com/1376815/82447688-e7a8bd00-9aa8-11ea-9a90-970a26fa53e3.png)
