### ISSUE TITLE
all these cards have the wrong font now, but the quality is good now

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#303]
He complains about the wrong fonts but I see it correct. Why is this happening?

![image](https://user-images.githubusercontent.com/1376815/82423711-7525e600-9a84-11ea-9790-52d6fc2e0bf1.png)

**Comment by ShkredovDmitriy** [comment]
![изображение](https://user-images.githubusercontent.com/38492536/82462649-81ca2e80-9ac4-11ea-96ee-a03cf108ee8f.png)
you sent me these svg images

**Comment by lpissinali** [comment]
Why I see it like this?
![image](https://user-images.githubusercontent.com/1376815/82463214-d1a4f780-9abc-11ea-84ff-4a12c89e3e01.png)

**Comment by ShkredovDmitriy** [comment]
the font in this photo is normal, I think he needs to clear the browser cache

**Comment by lpissinali** [comment]
He cleared several times. The font on your screenshot is also different than mine. Should I export the images with embeded fonts or something like that?

**Comment by ShkredovDmitriy** [comment]
fixed, I replaced all svg with png x3

**Comment by lpissinali** [comment]
Thanks for doing that, but I was discussing with the client yesterday and the problem was that when I open the sketch on adobe xd it doesn't show the assets as it would if you open on the sketch program on mac. So he'll send me the proper svgs and we'll replace once again later but I'll do that.
