### ISSUE TITLE
Add hover effect for the article menu

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#339]
![image](https://user-images.githubusercontent.com/1376815/82882873-f88e7e00-9f41-11ea-83fd-2270ce2124f4.png)

**Comment by ShkredovDmitriy** [comment]
https://prnt.sc/so6nld

**Comment by lpissinali** [comment]
Not opacity, it needs to have the underline as any other blue link

**Comment by ShkredovDmitriy** [comment]
Done? what about this links - https://prnt.sc/so7l3o?

**Comment by lpissinali** [comment]
Yes, they need the same effect as this link 
![image](https://user-images.githubusercontent.com/1376815/82926121-06aebf80-9f7f-11ea-8262-529eb631fc95.png)

**Comment by ShkredovDmitriy** [comment]
done
