### ISSUE TITLE
Please make the button expand on hover like the others

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#340]
![image](https://user-images.githubusercontent.com/1376815/82883177-6175f600-9f42-11ea-8ec1-aecb6ba56bf8.png)

**Comment by donrus** [comment]
Hover for this button we took from video

**Comment by lpissinali** [comment]
It was a mistake on the video

**Comment by ShkredovDmitriy** [comment]
Do you need only an extension or background change too?

**Comment by ShkredovDmitriy** [comment]
done

**Comment by lpissinali** [comment]
The background is fine but it should also grow. 
Same effect as this other button
![image](https://user-images.githubusercontent.com/1376815/82925730-6a84b880-9f7e-11ea-8aee-69d3b6efaea6.png)

**Comment by ShkredovDmitriy** [comment]
done.
