### ISSUE TITLE
Logo on text are not alligned

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#342]
![image](https://user-images.githubusercontent.com/1376815/82883348-95511b80-9f42-11ea-9c04-70a3cc410410.png)

**Comment by ShkredovDmitriy** [comment]
![изображение](https://user-images.githubusercontent.com/38492536/82923279-66a76500-9f83-11ea-8c2d-6c7db9f38ec7.png)

**Comment by ShkredovDmitriy** [comment]
this is svg image, this image is exported from Avocode.

**Comment by ShkredovDmitriy** [comment]
give me the correct image i will replace
