### ISSUE TITLE
EXTRA: Please make this section with a straight blue box. Images are attached. 

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#351]
![image](https://user-images.githubusercontent.com/1376815/82897005-377afe80-9f57-11ea-9f58-43301c0be71f.png)

![image](https://user-images.githubusercontent.com/1376815/82897040-46fa4780-9f57-11ea-927f-218d99465d4f.png)

![image](https://user-images.githubusercontent.com/1376815/82897055-4f528280-9f57-11ea-93db-9905bef4c704.png)

![image](https://user-images.githubusercontent.com/1376815/82897084-58435400-9f57-11ea-9edf-cd0e01019756.png)

**Comment by ShkredovDmitriy** [comment]
I do not see the attached images

**Comment by lpissinali** [comment]
Those are the last 3 images. The first one is how it is now

**Comment by ShkredovDmitriy** [comment]
I exported these pictures from Avocode, give me the correct pictures and I will replace them.

**Comment by lpissinali** [comment]
We don't need to export any pictures here, just make the box square instead of diagonal

**Comment by ShkredovDmitriy** [comment]
Done, check it

**Comment by lpissinali** [comment]
Good, thanks
