### ISSUE TITLE
let the animations fade in like on the rest of the page (currently it's triggered on scroll and too fast)

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#371]
![image](https://user-images.githubusercontent.com/1376815/83039475-85b6fd00-a03e-11ea-9210-e7aee8653d00.png)

**Comment by donrus** [comment]
I increase time from 1 to 2 sec

**Comment by lpissinali** [comment]
Can we make it make the animations fade in like on the other pages?

**Comment by donrus** [comment]
It is possible, but it will take several hours that we haven't got.

**Comment by donrus** [comment]
I look tomorrow if it would be simple I make it.

**Comment by lpissinali** [comment]
Thanks
