### ISSUE TITLE
animation is still bit too late

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#377]
![image](https://user-images.githubusercontent.com/1376815/83045851-78057580-a046-11ea-96d3-ecdac1e0a242.png)

**Comment by ShkredovDmitriy** [comment]
look, I made the start of the animation 20% earlier

**Comment by lpissinali** [comment]
It looks good to me but you forgot to remove the revert animation of this element
![image](https://user-images.githubusercontent.com/1376815/83264539-85df0600-a1c0-11ea-89ab-62172dff54d5.png)

**Comment by ShkredovDmitriy** [comment]
done
