### ISSUE TITLE
when you click on "show details" it shows the wrong icon

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#39]
![image](https://user-images.githubusercontent.com/1376815/80076060-e89f0b00-854b-11ea-9adf-e335fa967ea8.png)

**Comment by ShkredovDmitriy** [comment]
I do not have the right pictures

**Comment by ShkredovDmitriy** [comment]
give me this pictures in svg please, i can't export from sketch or avocode

**Comment by lpissinali** [comment]
Sent on upwork chat

**Comment by ShkredovDmitriy** [comment]
done
