### ISSUE TITLE
Subheader fonts

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#41]
The client is complaining about the font weight on the subheaders. I have here a comparison between the sketch (on the left) and the site. It does look a bit bolder using the SarabunSemiBold. When I turn it off and use SarabunRegular it looks better. Please check it out.

![image](https://user-images.githubusercontent.com/1376815/80076787-f5702e80-854c-11ea-950d-c512378eb5cf.png)

**Comment by ShkredovDmitriy** [comment]
https://prnt.sc/s4q8e3, I can offer medium font
