### ISSUE TITLE
Input behavior

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#43]
![image](https://user-images.githubusercontent.com/1376815/80077303-9959da00-854d-11ea-80a2-580d6369b5ec.png)

**Comment by lpissinali** [comment]
When you enter something in a form, it should always look like here https://www.sketch.com/s/gRjJJ/a/odMjoD/play 

(so the label moves up and you see the input of the user)

**Comment by donrus** [comment]
fixed
