### ISSUE TITLE
Error notification

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#56]
The error notification on the signin page should only show up if a user tries to login with a wrong email/pw. 

The message should be 
"Please try again.
Wrong email or password"

Also, please use the same red as in the user area (e.g. for the "cancel" buttons) and center the ! in the red square

![image](https://user-images.githubusercontent.com/1376815/80078652-81835580-854f-11ea-85d5-feddfd4764d4.png)

**Comment by donrus** [comment]
fixed
