### ISSUE TITLE
Adjust menu

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#7]
![Screenshot_7](https://user-images.githubusercontent.com/1376815/79629814-b016c000-814c-11ea-9693-2ec97cecbe53.png)

**Comment by lpissinali** [comment]
I added the language selection. Missing the bkg

**Comment by ShkredovDmitriy** [comment]
fixed

**Comment by lpissinali** [comment]
I think you did a mistake, I don't see the button to open the menu anymore

**Comment by ShkredovDmitriy** [comment]
fixed, make git pull
