### ISSUE TITLE
the drop down should open under it, not over it 

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#70]
![image](https://user-images.githubusercontent.com/1376815/80080716-4afb0a00-8552-11ea-89c9-8047a3a4aec5.png)

**Comment by donrus** [comment]
Can't do that with bootstrap-select. To do this I need to look source code of plugin. Is this issue critical?

**Comment by lpissinali** [comment]
I'll check, you can leave it for now.
