### ISSUE TITLE
this icon is wrong. besides this, it must point in the different direction once the dropdown is closed again

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#71]
![image](https://user-images.githubusercontent.com/1376815/80080794-6239f780-8552-11ea-9312-008977ab68e7.png)

**Comment by donrus** [comment]
fixed

**Comment by lpissinali** [comment]
Is it possible to show the icon up when the dropdown is opened?

**Comment by donrus** [comment]
fixed
