### ISSUE TITLE
Dropdown improvement

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#74]
on desktop/tablet the dropdown open in the wrong direction as well. 

it should contain a list of all countries and country codes.

when i start search in the input field, the dropdown should change accordingly. (e.g. if I type "U" I see Uganda, United Kingdom, etc)

![image](https://user-images.githubusercontent.com/1376815/80081093-c6f55200-8552-11ea-883e-7cfa50c60838.png)

**Comment by donrus** [comment]
fixed

**Comment by lpissinali** [comment]
Please add the area code on the field below instead.

![image](https://user-images.githubusercontent.com/1376815/80188849-0c2c8900-8612-11ea-846e-8a4c05ed01c2.png)

**Comment by lpissinali** [comment]
If I provide a json can you populate the list?

**Comment by donrus** [comment]
fixed

**Comment by lpissinali** [comment]
Can you remove the phone code from this place? 
![image](https://user-images.githubusercontent.com/1376815/80209296-1199cb80-8632-11ea-9e94-008d118f7eee.png)

**Comment by donrus** [comment]
fixed

**Comment by lpissinali** [comment]
Number cut out on mobile 
![image](https://user-images.githubusercontent.com/1376815/80471736-1e753280-8944-11ea-85aa-8f1c320a0721.png)

**Comment by donrus** [comment]
fixed
