### ISSUE TITLE
Please update those images

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#83]
![Group 16@2x](https://user-images.githubusercontent.com/1376815/80182457-3c225f00-8607-11ea-990d-bfee16f5c580.png)

Let me know if you need the export in a different format

**Comment by ShkredovDmitriy** [comment]
give me these pictures for desktop, tablet, mobile in svg, i can't export svg from sketch or avocado

**Comment by ShkredovDmitriy** [comment]
done
