### ISSUE TITLE
Missing cards, wrong margin

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/bitbunch#9]
![Screenshot_9](https://user-images.githubusercontent.com/1376815/79629881-30d5bc00-814d-11ea-9064-c5722a02e3d0.png)

**Comment by ShkredovDmitriy** [comment]
fixed

**Comment by lpissinali** [comment]
I still see the problem

**Comment by ShkredovDmitriy** [comment]
make git pull, and try again
